extends Node

const DEFAULT_CARD_MOVE_SPEED = 0.2
const DISCARD_SPEED = DEFAULT_CARD_MOVE_SPEED*2
const ACTION_ZONE_DRAW_INTERVAL = 0.025
const HAND_DRAW_INTERVAL = 0.35
const HAND_DISCARD_INTERVAL = 1.00

var globa_score : int = 0
